max_width = 60
wrap_comments = true
comment_width = 50
fn_call_width = 40
reorder_imports = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
use_field_init_shorthand = true
use_small_heuristics = "Max"
